name: Deploy via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      upload_additional_artifacts:
        description: 'Create addins (Firefox, Thunderbird, LibreOffice,...) (true/false)'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run pack-puter
        run: npm run pack-puter

      - name: Run pack-rumgr
        run: npm run pack-rumgr

      - name: Run pack-surmiran
        run: npm run pack-surmiran

      - name: Run pack-sursilv
        run: npm run pack-sursilv

      - name: Run pack-sutsilv
        run: npm run pack-sutsilv

      - name: Run pack-vallader
        run: npm run pack-vallader

      - name: Upload files via FTP
        if: ${{ github.event_name == 'push' || github.event.inputs.upload_additional_artifacts == 'false' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: /

      - name: Set up date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Upload build artifacts for web publication
        uses: actions/upload-artifact@v4.4.1
        with:
          name: web_${{ env.CURRENT_DATE }}
          path: build/web

      - name: Upload addins for Puter
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-puter_${{ env.CURRENT_DATE }}
          path: build/rm-puter

      - name: Upload addins for Rumantsch Grischun
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-rumgr_${{ env.CURRENT_DATE }}
          path: build/rm-rumgr

      - name: Upload addins for Surmiran
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-surmiran_${{ env.CURRENT_DATE }}
          path: build/rm-surmiran

      - name: Upload addins for Sursilvan
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-sursilv_${{ env.CURRENT_DATE }}
          path: build/rm-sursilv

      - name: Upload addins for Sutsilvan
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-sutsilv_${{ env.CURRENT_DATE }}
          path: build/rm-sutsilv

      - name: Upload addins for Vallader
        if: ${{ github.event.inputs.upload_additional_artifacts == 'true' }}
        uses: actions/upload-artifact@v4.4.1
        with:
          name: addins-vallader_${{ env.CURRENT_DATE }}
          path: build/rm-vallader

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Set Slack message payload
        id: slack_payload
        run: |
          if [[ "${{ needs.build.result }}" == "success" ]]; then
            echo "color=#36a64f" >> $GITHUB_ENV  # Green color
            echo "status_text=Succeeded" >> $GITHUB_ENV
            echo "icon=white_check_mark" >> $GITHUB_ENV
          else
            echo "color=#ff0000" >> $GITHUB_ENV  # Red color
            echo "status_text=Failed" >> $GITHUB_ENV
            echo "icon=x" >> $GITHUB_ENV
          fi

      - name: Send Slack notification on success or failure
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ env.color }}",
                  "text": "*Installation of new spellchecker version* (run *${{ github.run_number }}*) has *${{ env.status_text }}*.",
                  "fields": [
                    {
                      "title": "Job Status",
                      "value": "${{ env.status_text }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    }
                  ]
                }
              ],
              "username": "GitHub Actions Bot",
              "icon_emoji": ":${{ env.icon }}:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack notification on failure only
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000",
                  "text": "*Installation of new spellchecker version* (run *${{ github.run_number }}*) has *Failed*.",
                  "fields": [
                    {
                      "title": "Job Status",
                      "value": "Failed",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    }
                  ]
                }
              ],
              "username": "GitHub Actions Bot",
              "icon_emoji": ":x:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ALARM }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
